version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo installing nodejs...
      - curl -sL https://rpm.nodesource.com/setup_18.x | sudo -E bash -
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install --legacy-peer-deps
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --configuration production
artifacts:
  files:
    - "**/*"
    - appspec.yaml
    - scripts/**/*
  discard-paths: no
  base-directory: dist/
