version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - aws ec2 describe-instances --filters  "Name=instance-state-name,Values=stopped" --query 'Reservations[].Instances[].Tags[?Key==`Name`].Value[]' --output text | xargs -I {} aws deploy update-deployment-group     --application-name angular-dashboard-app  --current-deployment-group-name angular-dashboard-group   --ec2-tag-filters Key=Name,Type=KEY_AND_VALUE,Value={}
      - aws ec2 describe-instances --filters  "Name=instance-state-name,Values=stopped" --query "Reservations[*].Instances[*].[InstanceId]" --output text | xargs -I {} aws ec2 start-instances --instance-ids {}
      - id=$(aws ec2 describe-instances --filters  "Name=instance-state-name,Values=stopped" --query "Reservations[*].Instances[*].[InstanceId]" --output text --region ap-south-1)
      - echo $id
      - echo installing nodejs...
      - curl -sL https://rpm.nodesource.com/setup_18.x | sudo -E bash -
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install --legacy-peer-deps
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --configuration production
  post_build:
    commands:
      - mv appspec.yml ./dist
      - mv scripts ./dist 
      - if [[ $id == i-0594407c5c6c26a9e ]]; then
    aws elbv2 modify-listener --listener-arn "arn:aws:elasticloadbalancing:ap-south-1:422886226081:listener/app/angular-ALB/0600ebb8088a347a/0d115ea7ee4b2419" --default-action '[{
      "Type": "forward",
      "Order": 1,
      "ForwardConfig": {
        "TargetGroups": [
            {"TargetGroupArn": "arn:aws:elasticloadbalancing:ap-south-1:422886226081:targetgroup/angular-app-tg/5d22faad0e815358", "Weight": 1 },
            {"TargetGroupArn": "arn:aws:elasticloadbalancing:ap-south-1:422886226081:targetgroup/angular-app-tg-02/ea1f53c0bb1c4caa", "Weight": 0 }
        ]
      }
   }]' --region ap-south-1
else
  aws elbv2 modify-listener --listener-arn "arn:aws:elasticloadbalancing:ap-south-1:422886226081:listener/app/angular-ALB/0600ebb8088a347a/0d115ea7ee4b2419" --default-action '[{
      "Type": "forward",
      "Order": 1,
      "ForwardConfig": {
        "TargetGroups": [
            {"TargetGroupArn": "arn:aws:elasticloadbalancing:ap-south-1:422886226081:targetgroup/angular-app-tg/5d22faad0e815358", "Weight": 0 },
            {"TargetGroupArn": "arn:aws:elasticloadbalancing:ap-south-1:422886226081:targetgroup/angular-app-tg-02/ea1f53c0bb1c4caa", "Weight": 1 }
        ]
      }
   }]' --region ap-south-1
fi
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
 
